services:
  db:
    image: postgres
    restart: always
    ports:
      - "54100:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: clojurians_log
      # POSTGRES_DB: doesarchive
